// <auto-generated />
using System;
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250528210941_AddConfigurationsAndSeedData")]
    partial class AddConfigurationsAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city_name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Barcelona"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BRA",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "POR",
                            CountryName = "Portugal"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "ESP",
                            CountryName = "Espanha"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("property_name");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_night");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hotel Copacabana Palace",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Pousada Ipanema",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Hotel Unique",
                            PricePerNight = 380.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Apartamento Vila Madalena",
                            PricePerNight = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Name = "Pousada do Torel",
                            PricePerNight = 95.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            Name = "Hotel Infante Sagres",
                            PricePerNight = 140.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 5,
                            Name = "Hotel Ritz Madrid",
                            PricePerNight = 320.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            Name = "Casa Bonay",
                            PricePerNight = 85.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
